import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useEffect, useState } from "react";

export default function Home() {
  const [items, setItems] = useState(null);

  useEffect(() => {
    // fetching
    setItems([
      { title: "제목", content: "내용" },
      { title: "제목2", content: "내용2" },
    ]);
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>{items && <Items posts={items} />}</main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
export function Items(props) {
  const { posts } = props;

  return (
    <ul>
      {posts.map((post) => (
        <li key={post.title}>
          {post.title} {post.content}
        </li>
      ))}
    </ul>
  );
}
